import * as S from "./styles";
export const Skills = () => {
    return(
        <S.SecondCardContainer>
            <S.CardSkill>
               <S.Freact/>
            </S.CardSkill>
            <S.CardSkill>
               <S.Fnode/>
            </S.CardSkill>
            <S.CardSkill>
               <S.Snest/>
            </S.CardSkill>
            <S.CardSkill>
               <S.Stypescript/>
            </S.CardSkill>
            <S.CardSkill>
               <S.Spostgres/>
            </S.CardSkill>
            <S.CardSkill>
               <S.Sstyled/>
            </S.CardSkill>
            <S.CardSkill>
               <S.Svercel/>
            </S.CardSkill>
            <S.CardSkill>
               <S.Saws/>
            </S.CardSkill>
            <S.CardSkill>
               <S.Sprismma/>
            </S.CardSkill>
        </S.SecondCardContainer>
    )
};